### ISSUE TITLE
Hlasování – Chyba při hlasování nepřihlášeného uživatele

### ISSUE THREAD

**Issue by jakubboucek** [techheavencz/barcamp#12]
Branch: `hlasovani`

Na stránku `/conference/talks-voting` se dostane kdokoliv i nepřihlášený. To ale vede k chybě `Call to a member function getId() on null` na řádku:
https://github.com/techheavencz/barcamp/blob/874995f15cce84c3b3aff77031b2b382e69ff209/app/presenters/ConferencePresenter.php#L67

**Comment by plexp** [comment]
Pracuji na tom

**Comment by plexp** [comment]
Ošetřeno
