### ISSUE TITLE
Hlasování - neošetřené opakované hlasování

### ISSUE THREAD

**Issue by jakubboucek** [techheavencz/barcamp#14]
Branch: `hlasování`

Oprakovaným hlasování jednoho uživatele se jeho hlasy sčítají. Je to žádoucí?

Náhled na tabulku `voting`:
![image](https://user-images.githubusercontent.com/1657322/54272536-31804400-4584-11e9-8e83-512dd072a84e.png)

V ideální případě by hlasování mělo jeho nová volba "nahradit" tu původní. Tedy smazat hlasy, pro které není nyní hlasováno.

**Comment by plexp** [comment]
Zamezeno opakovanému hlasování pro tu samou přednášku
