### ISSUE TITLE
Hlasování – Uživatel nemůže zjistit, zda už hlasoval

### ISSUE THREAD

**Issue by jakubboucek** [techheavencz/barcamp#15]
Branch: `hlasovani`

Když uživatel odhlasuje, tak se web tváří, jako by nikdy nehlasoval (kromě zobrazení stránky těsně po odeslání, viz #13). 

Bylo by dobré, aby uživatel trvale viděl, pro co hlasoval, nebo alespoň informaci, že už hlasoval. 

V ideálním případě by měl mít možnost svoji volbu změnit, viz #14; v horším případě pak zamezit druhému hlasování.

**Comment by plexp** [comment]
Hlasování se nepromazává - místo toho zůstanou zaškrtlé ty přednášky, co člověk naposledy vybral, tj. ty, ke kterým má daný hlas.
